### ISSUE TITLE
boolean.pm values cannot be emitted

### ISSUE THREAD

**Issue by eserte** [perlpunk/YAML-PP-p5#37]
boolean.pm values cannot be emitted with YAML::PP 0.24:
```
$ perl5.30.3 -Mboolean -MYAML::PP -E '$p=YAML::PP->new; say $p->dump_string([true,false])'  
Reftype SCALAR not implemented at /opt/perl-5.30.3/lib/site_perl/5.30.3/YAML/PP/Representer.pm line 120.
```

Possible workaround: specify `boolean=>"boolean"` (but why? this should only be a load-time option?):
```
$ perl5.30.3 -Mboolean -MYAML::PP -E '$p=YAML::PP->new(boolean=>"boolean"); say $p->dump_string([true,false])' 
---
- true
- false
```

**Comment by perlpunk** [comment]
The strategy is that only one boolean type can be loaded and dumped, `boolean`, `JSON::PP` or `1/0`.
That's why you have to set the `boolean` option in the object.
It's kind of strict.

The error message could of course be a bit confusing.
If you add `Perl` to the schema, then the boolean objects will be dumped as ordinary objects:

```
perl -wE'
use YAML::PP;
my $yp = YAML::PP->new( schema => [qw/ + Perl /] );
use boolean;
say $yp->dump_string([true, false])'
---
- !perl/scalar:boolean
  =: 1
- !perl/scalar:boolean
  =: 0
```
Maybe the error message should add that as a hint.

**Comment by perlpunk** [comment]
I just released 0.025 with an improved error message.

**Comment by eserte** [comment]
Somehow I don't like the asymmetry --- for dumping as perl objects, `schema` should be set, for dumping as true/false, `boolean` needs to set.
Also, is there any reason why it's not possible to dump different boolean-like objects (JSON::PP, boolean) at the same time? Is this a limitation due to the current implementation?

**Comment by perlpunk** [comment]
It's not asymmetric if you know how it's implemented.
The default schema (Core) is supposed to handle strings, numbers, hashes, arrays and booleans.
Because there are no booleans in perl, I added an option `boolean` to specify which boolean implementation should be used. This option existed before I added te `schema` option.

Now, as YAML is a serialization language, it's supposed to be able to serialize also everything that goes beyond the standard types of the Core schema. That's done with the Perl schema.
By default I wouldn't want it to serialize JSON::PP/boolean objects to booleans, because that could mean loss of information.

The `boolean` option should rather be an option to the Core schema instead of a YAML::PP option.

It would be possible to support multiple bool classes at once by specifying an array. That would be a pretty simple change.
It's just that I did not come across such a use case, but if you see one, I'll give it a shot :)

**Comment by eserte** [comment]
> It's not asymmetric if you know how it's implemented.

Yeah, I feared that this is the reason ;-)

So, to summarize, for the both most prominent use cases one would do the following:
* serializing for the same application or another perl application: `schema => ["Perl"]`
* serializing for a non-perl application: `schema => ["Core"], boolean => "__ANY__"`

I am using `__ANY__` here as a placeholder for all boolean types supported by `YAML::PP` --- currently this would probably be the same as `[qw(JSON::PP boolean)]` (if the array notion was implemented). If `YAML::PP` would support more types in future it would go automatically into this array. I would prefer if `__ANY__` could also be spelled as `undef` and actually be omitted --- yes, I still think that auto-detection would be preferable here.

What are the use cases for supporting multiple boolean types? The data could be created by a 3rd party module, and the boolean type used in that module could change in later releases. Or the module checks which boolean class from a list of supported modules is installed, and would suddenly use another if a module in front of the list was newly installed. Or it could be a general purpose data dumper which is as human-readable as possible (so should dump `false`/`true` instead of `!perl/...`).

**Comment by perlpunk** [comment]
Ok, maybe supoorting dumping all types by default is not such a bad idea.
The default for loading would still be `perl`.
How about adding a star to the boolean option like this: `boolean,*` would dump all supported types, and load all booleans as `boolean` objects?

**Comment by eserte** [comment]
What's the exact syntax and semantics for it? A possibly comma-separated string, with left value for loading and right value for dumping? And if there's only a single value, then this one is used for both loading and dumping? And a star for loading would mean something like "the first supported and available boolean-handling class"?

**Comment by perlpunk** [comment]
My thinking was that you specify the modules you want to support for dumping, comma separated, and the first one will be the one used for loading. A star stands for al supported modules.

So a single star would mean "use perl booleans for loading, and dump all supported modules".
And I would make this the default.
It might look a bit like overkill, but there might be other boolean modules in the future.

What do you think?

**Comment by eserte** [comment]
I think this could work.

**Comment by bpj** [comment]
👍  We get data from different sources, sometimes loaded with JSON[/PP].pm and sometimes with YAML::PP using boolean.pm, preferred because of its interface and then dump them with YAML::PP. Currently we do some Data::Rmap shenanigans to normalize booleans. It would be good if we didn't have to do that.

**Comment by perlpunk** [comment]
oh, I forgot about this ticket... :(
Will try to do this next weekend.

**Comment by perlpunk** [comment]
also we now have experimental 5.36 boolean support: https://metacpan.org/release/TINITA/YAML-PP-0.033_002

**Comment by perlpunk** [comment]
@bpj you mean, something like `boolean => 'perl0'` would load `true` as 1 and `false` as 0?
Should be fairly easy. For what would you need it?
